### ISSUE TITLE
bug: sometimes compare shows no lists

### ISSUE THREAD

**Issue by procodix** [L13/vscode-diff#137] opened 2023-09-07 07:34 UTC
When selecting two folders, more often than not, the extension shows no file lists. Restarting VSCode sometimes helps, but sometimes it takes 5-6 iterations (close, restart, open extension, double click history item), until the file list appears.

**Comment by L13** [comment] 2023-09-08 10:44
Hi, I have never experienced such a problem. I still have done tens of thousands of comparisons and never saw an issue like this. If it happens randomly it sounds like a bigger problem with vscode itself. I have tested the extension on all platforms and it always worked.  Which OS do you have? Are all filters (deleted, modified,...) enabled? Is the search disabled? Sometimes the webview has loading issues but if this happens a dialog appears and you can try it again and then it works.

**Comment by L13** [comment] 2023-09-12 22:40
If a file is not readable an error message occurs. If you disable "Abort On Error" the scan completes and shows the list. If a file or folder is not accessible it is marked as unknown. So if you don't see any error message it must be something different. Are there any error messages in the console? (Help > Toggle Developer Tools)

**Comment by L13** [comment] 2024-02-29 06:32
I can reproduce the bug, but after some testing it doesn't seem easy to solve. I try to find a solution.

**Comment by L13** [comment] 2024-03-10 16:54
Hi, I published the new version with the fix. After one week of testing and mashing the mouse button the issue didn't appear any more. I recommend not to double because it isn't necessary otherwise a compare can be triggered twice. The tree view of an extension only supports single click.

**Closed by L13** 2024-03-10 16:54 UTC
