### ISSUE TITLE
merge feature request

### ISSUE THREAD

**Issue by hongshui3000** [L13/vscode-diff#113] opened 2022-03-10 08:51 UTC
Hope to add file merge function, similar to this extension : https://github.com/moshfeu/vscode-diff-merge

**Comment by L13** [comment] 2022-03-11 08:19
Hi, the feature is out of scope because I'm using the VS Code Diff Editor. Writing an extension like this means way more work. The issue is that the internal Diff Editor can not be extended and writing an own one is far beyond of a normal extension, because it means you have to rebuild every VS Code Editor feature, because the Webview of VS Code has no access to the internal api. You can open an issue on the vscode github repository and ask the Vs Code team if they extend their Diff Editor with the features you want.

**Closed** 2022-03-11 08:19 UTC
